name: Auto run
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - run: pip install -r requirements.txt
    - run: python main.py
    - name: push repo
      run: |
        git config core.ignorecase false
        git config --local user.name "github-actions"
        git config --local user.email "action@github.com"
        git add .
        git commit -m "Updated on $(date '+%Y-%m-%d %H:%M:%S')"
        git push
